### ISSUE TITLE
AttributeError: 'function' object has no attribute 'validators'

### ISSUE THREAD

**Issue by mplemay** [hatchet-dev/hatchet-python#281]
The code below produces the following error:
```python
from asyncio import run

from hatchet_sdk import Context

from brugge.globals import HATCHET


@HATCHET.function(name="act")
async def act(context: Context) -> None:
    action = context.data.get("action", None)
    context.log(action)


async def main() -> None:
    worker = HATCHET.worker(name="backend", max_runs=1)
    await worker.async_start()

if __name__ == "__main__":
    run(main())
```
```
Traceback (most recent call last):
  File "/Users/matthewlemay/Github/brugge/src/brugge/workflows/worker.py", line 4, in <module>
    from brugge.workflows.action import act  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewlemay/Github/brugge/src/brugge/workflows/action.py", line 6, in <module>
    @HATCHET.function(name="act")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewlemay/Github/brugge/.venv/lib/python3.12/site-packages/hatchet_sdk/v2/hatchet.py", line 151, in wrapper
    wrapped_resp = resp(func)
                   ^^^^^^^^^^
  File "/Users/matthewlemay/Github/brugge/.venv/lib/python3.12/site-packages/hatchet_sdk/v2/hatchet.py", line 35, in inner
    return HatchetCallable(
           ^^^^^^^^^^^^^^^^
  File "/Users/matthewlemay/Github/brugge/.venv/lib/python3.12/site-packages/hatchet_sdk/v2/callable.py", line 45, in __init__
    self.validators = func.validators
                      ^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'validators'
```

**Comment by hatchet-temporary** [comment]
Hey @mplemay, looking into this! looks like a bug in something we just shipped (Pydantic support)

**Comment by mplemay** [comment]
@hatchet-temporary Thanks for the fix!
